### ISSUE TITLE
Backlinks auf neue Kataloge umstellen

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#283]
## Task

In swissbib grün und jusbib müssen die Backlinks in den Exemplaren auf die neuen Kataloge (primo, ebsco in St. Gallen) umgestellt werden. Diese bieten die allermeisten Benutzerfunktionen an und sind unterdessen bekannter als die Aleph- und Virtua-OPACs. Für IDS Basel Bern bereits gemacht.
## Info

Doku für primo : https://developers.exlibrisgroup.com/primo/apis/deeplinks

> Kommentar James:
> "Allerdings denke ich dass Links in Format "Permanenter Link" einfacher und geeigneter wären.
> http://iluplus.hosted.exlibrisgroup.com/41ZBL:institution_scope:41ZBL_Aleph001181375 
> Die 9-stellige Nummer an Ende ist die Aleph-SN. Damit landet man auf dem "Details-Tab" des Titels. >Besser wäre der Tab "Standort/Bestellen", wo eben Standort, Verfügbarkeit und Bestelloptionen zur >Verfügung stehen, aber Primo unterstützt dies (noch) nicht."
## wichtig

Eine Anmeldung nach Permalink-Aufruf funktioniert bei Primo nicht, es sei denn, man war schon angemeldet und entsprechend mit cookie versehen! Deshalb müssen entsprechende Verbünde wieder auf Aleph umgestellt werden. 
## Stand
- [x] IDS Basel Bern : swissbib Basel Bern
- [x] NEBIS : Stabiler Permalink -> geht nicht wegen Primo-Bug
- [x] RERO : explore
- [x] IDSLU :iluplus -> geht nicht wegen Primo-Bug
- [x] HSG : ebsco (bzw. eigenes Interface)
- [x] SGBN : wcl???

**Comment by liowalter** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/swissbib/vufind/issues/283](https://trello.com/c/djymFRrC/201-https-githubcom-swissbib-vufind-issues-283)

**Comment by witzigs** [comment]
erledigt für alle genannten, daher geschlossen
