### ISSUE TITLE
Bookbag / Zwischenablage

### ISSUE THREAD

**Issue by oschihin** [swissbib/vufind#359]
## Beschreibung
Mit Commit e4a1f9274c91806c09e8adb6e282e43a82bd9c00 wurde die grundlegende Bookbag- oder Zwischenablage-Funktionalität konfiguriert. Sie ist noch unvollständig und ungetestet. Für produktiven Release noch abschalten, wenn untere Punkte nicht gelöst sind.

## Tasks
* [x] Möglichkeit, ausgewählte Titel auf der Trefferliste in die Zwischenablage zu legen
* [ ] Design der Checkboxen anschauen, für gut befinden oder verbessern
* [ ] Funktionalität in der Merkliste prüfen
* [x] Testen mit Anmeldung. Aktuell wird ein Popup angezeigt

**Comment by guenterh** [comment]
@edelm 
Hallo Matthias,

wie heute morgen besprochen, mit Shibboleth haben wir ein Problem bei PopUps.
Möglichkeiten die ich sehe:
a) wir benutzen den Mechanismus wie bisher (Umleitung auf die singlePage Login ohne PopUp)
mögliches Problem: Anzeige des Dialogs für save etc. nach erfolgreicher Anmeldung (bisher im Popup), aber stabiler in der Funktionalität auch wenn möglicherweise weniger benutzerfreudlich

b) wir versuchen shibboleth im PopUp zu implementieren. Kann aber mit Bezug zu unserem going public auf Basis VF 2.5 risikoreich sein, da Nebeneffekte mit hoher Wahrscheinlichkeit nicht auszuschliessen sind.

@oschihin  zur Info
@maechler : Markus, können wir das am Donnerstag mal besprechen?

Günter

**Comment by edelm** [comment]
Ich hab mal b) (Login im Popup) versucht. Die JS Konsole wirft "A call to document.write() from an asynchronously-loaded external script was ignored.". Das js von Switch verwendetr document.write.
- Wird das login.phtml in einem anderen (asynchronen) Kontext aufgerufen, wenn man es innerhalb des Popups rendert?
- Können wir evtl selber präziser als mit document.write steuern, an welche Stelle das Switch-Login gerendert werden soll? (=anpassen des JS von Switch)

**Comment by guenterh** [comment]
@edelm 
Hallo Matthias

stimmt - jetzt kommt es mir wieder in den Sinn, über document.write bin ich auch seinerzeit gestossen.
Anpassen könnten wir schon. Das Problem dabei: Wenn switch etwas ändert, bekommen wir das nicht mit. So wie ich das jetzt sehe, sind Änderungen nicht sehr wahrscheinlich bzw. sollte in der Regel keine grösseren Probleme mehr verursachen. Ich habe mich seinerzeit etwas dagegen gesträubt, ein eigenes script zu verwenden. Könnte man aber machen.

Was das noch sonst bedeutet, kann ich im Moment nicht so gut abschätzen. Lass uns morgen darüber reden.

**Comment by guenterh** [comment]
@edelm @witzigs 
Hallo Matthias
habe wegen der bookbag ein wenig suchen müssen. Dachte es sei immer nur einfaches Ausschalten von JavaScript gewesen. Im Prinzip ist es das auch. Nur sind die Wege dazu immer ein wenig unterschiedlich.... Vielleicht schaffen wir es ja mal (zusammen mit VuFind) dies zu vereinheitlichen

Im konkreten Fall muss die Registrierung auf den click event einer Funktion unterbunden werden.
https://github.com/swissbib/vufind/blob/master/themes/bootstrap3/js/cart.js#L183

$(document).ready(function() {
  $( '#cartItems' ).unbind();
});

Das Problem ist, dass man nicht einfach einen zusätzchen command in eine swissbib java-Script Datei aufnehmen kann (https://github.com/swissbib/vufind/blob/master/themes/sbvfrd/theme.config.php), da der VuFind Mechanismus diese 'vor' cart.js aufnimmt und damit das unbind nicht mehr wirksam ist.

Auf 'die Schnelle' habe ich es so gemacht, dass ich im Head-tag von
https://github.com/swissbib/vufind/blob/master/themes/sbvfrd/templates/layout/layout.phtml
diesen ViewHelper 
$this->headScript()->appendFile("/vfrd/themes/sbvfrd/js/swissbib/swissbibAppend.js"
aufgerufen habe (in swissbibAppend.js steht dann jQuery Konstrkt wie oben - nicht im repository)

Unschön ist hier der Pfad. Habe auf die Schnelle nicht gesehen, wie der Pfad sonst gefunden werden kann. Kannst Du das mal schauen? Der ViewHelper referenziert einen Typ VuFindThemeInfo. Dieser ist ganz interessant zum Anschauen, da hier die Hierarchien behandelt werden. Lohnt sich mal anzusehen.

Das Ergebnis: die Popup-Box erscheint nicht mehr. Nicht der Schönheit letzter Schrei, aber ich könnte damit leben.

Viele Grüsse, Günter

**Comment by oschihin** [comment]
Wir bieten vorderhand keinen bookbag bzw. Zwischenablage an.
