### ISSUE TITLE
Konfiguration Facetten

### ISSUE THREAD

**Issue by witzigs** [swissbib/vufind#389]
Fortsetzung von #69

Sammelissue für offene und zu diskutierende Punkte in Bezug auf die Konfiguration von OR- und NOT-Facetten sowie die hierarchische Formatfacette.

**Grundsätzlich**
- Konfiguration ob Einträge mit OR oder AND kombiniert werden sollen, ist pro Facette möglich
- Konfiguration ob NOT angeboten werden soll, ist pro Facette möglich
- Konfiguration ist über facets.ini gesteuert, unterschiedliche Konfigurationen für die drei Oberflächen sind möglich
- Auf testbaselbern zum Testen konfiguriert: Facette Genre/Form exemplarisch nur mit OR, ohne NOT, Facette Sprache nur mit NOT, ohne OR, restliche Facetten mit OR und NOT

**ToDo - Design**
- [x] Facetteneinträge in Textfarbe, nicht Linkfarbe
- [x] Kästchen bei OR-Facetten? 
- [x] Hierarchische Facetten: Hochkomma als Tausendertrennzeichen definieren

**ToDo - hierarchische Formatfacette**
- [x] Übersetzungen Formatcodes ergänzen
- [x] Alphabetische Sortierung? Ist möglich für Top-Level oder für alle Levels (auf testbaselbern für alle Levels konfiguriert)

**ToDo - OR/NOT**
- [x] Konfiguration muss auch für Favoritenfacette funktionieren
